objects/Author__c.object
<CustomObject>
    <fields>
        <fullName>Author_Name__c</fullName>
        <description>Captures the full name of the Author</description>
        <label>Author Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>Captures the First Name of the Book Author</description>
        <label>First Name</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Captures the Last Name of the Book Author</description>
        <label>Last Name</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Author</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Author</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Authors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Author_Trigger_Handler.cls
public with sharing class Author_Trigger_Handler
{
	private final List<Author__c> records;
	private final List<Author__c> oldRecords;

	public Author_Trigger_Handler
			(List<Author__c> records, List<Author__c> oldRecords)
	{
		this.records = records;
		this.oldRecords = oldRecords;
	}

	public void beforeInsert()
	{
		setAuthorFullNameFromFirstAndLastNames();
	}

	public void beforeUpdate()
	{
		setAuthorFullNameFromFirstAndLastNames();
	}

	public void beforeDelete()
	{
		// To Do
		// Add required logic while Deleting Opportunity Line Item
	}

	private void setAuthorFullNameFromFirstAndLastNames()
	{
		for (Author__c record : records)
		{
			record.Author_Name__c = record.First_Name__c + ' ' + record.Last_Name__c ;
		}
	}
}