objects/Author__c.object
<CustomObject>
    <fields>
        <fullName>Author_Name__c</fullName>
        <description>Captures the full name of the Author</description>
        <label>Author Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Author</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Author</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Authors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Book__c.object
<CustomObject>
    <fields>
        <fullName>Genre__c</fullName>
        <description>Defines the Genre of the Book</description>
        <label>Genre</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Action</fullName>
                </value>
                <value>
                    <fullName>Adventure</fullName>
                </value>
                <value>
                    <fullName>Art</fullName>
                </value>
                <value>
                    <fullName>Children’s</fullName>
                </value>
                <value>
                    <fullName>Comedy</fullName>
                </value>
                <value>
                    <fullName>Contemporary</fullName>
                </value>
                <value>
                    <fullName>Cooking</fullName>
                </value>
                <value>
                    <fullName>Development</fullName>
                </value>
                <value>
                    <fullName>Drama</fullName>
                </value>
                <value>
                    <fullName>Dystopian</fullName>
                </value>
                <value>
                    <fullName>Fable</fullName>
                </value>
                <value>
                    <fullName>Fairy Tale</fullName>
                </value>
                <value>
                    <fullName>Families &amp; Relationships</fullName>
                </value>
                <value>
                    <fullName>Fantasy</fullName>
                </value>
                <value>
                    <fullName>Fiction</fullName>
                </value>
                <value>
                    <fullName>Folklore</fullName>
                </value>
                <value>
                    <fullName>Guide / How-to</fullName>
                </value>
                <value>
                    <fullName>Health</fullName>
                </value>
                <value>
                    <fullName>Historical</fullName>
                </value>
                <value>
                    <fullName>Historical fiction</fullName>
                </value>
                <value>
                    <fullName>History</fullName>
                </value>
                <value>
                    <fullName>Horror</fullName>
                </value>
                <value>
                    <fullName>Humor</fullName>
                </value>
                <value>
                    <fullName>Memoir</fullName>
                </value>
                <value>
                    <fullName>Motivational</fullName>
                </value>
                <value>
                    <fullName>Mystery</fullName>
                </value>
                <value>
                    <fullName>Paranormal</fullName>
                </value>
                <value>
                    <fullName>Romance</fullName>
                </value>
                <value>
                    <fullName>Science Fiction</fullName>
                </value>
                <value>
                    <fullName>Self-help / Personal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Publishing_House__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Captures the Publishing House company where the books was published</description>
        <label>Publishing House</label>
        <referenceTo>Publishing_House__c</referenceTo>
        <relationshipLabel>Books</relationshipLabel>
        <relationshipName>Books</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Book</label>
    <nameField>
        <displayFormat>B-{000000}</displayFormat>
        <label>Book Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/BookAuthor__c.object
<CustomObject>
    <description>Many to Many Relationship between Book and Authors</description>
    <fields>
        <fullName>Author_Name__c</fullName>
        <formula>Author__r.First_Name__c +  &apos; &apos; + Author__r.Last_Name__c</formula>
        <label>Author Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Author__c</fullName>
        <description>Captures the Author Name os the Book</description>
        <label>Author Id</label>
        <referenceTo>Author__c</referenceTo>
        <relationshipLabel>BookAuthors</relationshipLabel>
        <relationshipName>BookAuthors</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Book__c</fullName>
        <description>Name of the Books</description>
        <label>Book Id</label>
        <referenceTo>Book__c</referenceTo>
        <relationshipLabel>BookAuthors</relationshipLabel>
        <relationshipName>BookAuthors</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>BookAuthor</label>
    <nameField>
        <displayFormat>BAN-{000000}</displayFormat>
        <label>BookAuthor Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BookAuthors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Publishing_House__c.object
<CustomObject>
    <label>Publishing House</label>
    <nameField>
        <displayFormat>PHN-{000000}</displayFormat>
        <label>Publishing House Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publishing Houses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/GetNumberOfBooks.cls
public with sharing class GetNumberOfBooks
{
	@AuraEnabled(Cacheable=true)
	public static List<AggregateResult> getNumberOfBooksByGenre(Id publishingHouseId)
	{
		try
		{
			return
			[
					SELECT
							COUNT(Id) bookCount,
							Genre__C genre
					FROM Book__C
					WHERE Publishing_House__C = :publishingHouseId
					GROUP BY Genre__C
			];
		}
		catch (Exception error)
		{
			AuraHandledException auraException = new AuraHandledException(error.getMessage());
			auraException.setMessage(error.getStackTraceString());
			throw auraException;
		}
	}

	@AuraEnabled(Cacheable=true)
	public static List<AggregateResult> getNumberOfBooksByAuthor(Id publishingHouseId)
	{
		try
		{
			return
			[
					SELECT
							COUNT(ID) bookCount,
							author__r.Author_Name__c authorName
					FROM BookAuthor__c
					WHERE Book__C IN
					(
							SELECT
									Id
							FROM Book__C
							WHERE Publishing_House__C = :publishingHouseId
					)
					GROUP BY author__r.Author_Name__c
			];
		}
		catch (Exception error)
		{
			AuraHandledException auraException = new AuraHandledException(error.getMessage());
			auraException.setMessage(error.getStackTraceString());
			throw auraException;
		}
	}
}