objects/Author__c.object
<CustomObject>
    <label>Author</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Author</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Authors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Book__c.object
<CustomObject>
    <label>Book</label>
    <nameField>
        <displayFormat>B-{000000}</displayFormat>
        <label>Book Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/BookAuthor__c.object
<CustomObject>
    <description>Many to Many Relationship between Book and Authors</description>
    <fields>
        <fullName>Author__c</fullName>
        <description>Captures the Author Name os the Book</description>
        <label>Author Id</label>
        <referenceTo>Author__c</referenceTo>
        <relationshipLabel>BookAuthors</relationshipLabel>
        <relationshipName>BookAuthors</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>BookAuthorName__c</fullName>
        <description>To avoid duplicate entries of Book and Author combination</description>
        <label>BookAuthorId</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Book__c</fullName>
        <description>Name of the Books</description>
        <label>Book Id</label>
        <referenceTo>Book__c</referenceTo>
        <relationshipLabel>BookAuthors</relationshipLabel>
        <relationshipName>BookAuthors</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>BookAuthor</label>
    <nameField>
        <displayFormat>BAN-{000000}</displayFormat>
        <label>BookAuthor Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BookAuthors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/BookAuthor_Trigger_Handler.cls
public with sharing class BookAuthor_Trigger_Handler
{
	private final List<BookAuthor__c> records;
	private final List<BookAuthor__c> oldRecords;

	public BookAuthor_Trigger_Handler
			(List<BookAuthor__c> records, List<BookAuthor__c> oldRecords)
	{
		this.records = records;
		this.oldRecords = oldRecords;
	}

	public void beforeInsert()
	{
		setBookAuthorKeyFromBookAndAuthorIds();
	}

	public void beforeUpdate()
	{
		setBookAuthorKeyFromBookAndAuthorIds();
	}

	public void beforeDelete()
	{
		// To Do
		// Add required logic while Deleting Opportunity Line Item
	}

	private void setBookAuthorKeyFromBookAndAuthorIds()
	{
		for (BookAuthor__c record : records)
		{
			record.BookAuthorName__c = record.Book__c + '' + record.Author__c;
		}
	}
}