objects/Book__c.object
<CustomObject>
    <fields>
        <fullName>Publishing_Date__c</fullName>
        <description>Records the date when the book was published by a Publishing House</description>
        <label>Publishing Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Publishing_House__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Captures the Publishing House company where the books was published</description>
        <label>Publishing House</label>
        <referenceTo>Publishing_House__c</referenceTo>
        <relationshipLabel>Books</relationshipLabel>
        <relationshipName>Books</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Book</label>
    <nameField>
        <displayFormat>B-{000000}</displayFormat>
        <label>Book Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Publishing_House__c.object
<CustomObject>
    <fields>
        <fullName>Last_Published_Date__c</fullName>
        <description>Field to store the Calculated value of the publishing date of the last released book of each Publishing House record</description>
        <label>Last Published Date</label>
        <type>Date</type>
    </fields>
    <label>Publishing House</label>
    <nameField>
        <displayFormat>PHN-{000000}</displayFormat>
        <label>Publishing House Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publishing Houses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Book_Trigger_Handler.cls
public with sharing class Book_Trigger_Handler
{
	private final List<Book__c> records;
	private final List<Book__c> oldRecords;

	public Book_Trigger_Handler
			(List<Book__c> records, List<Book__c> oldRecords)
	{
		this.records = records;
		this.oldRecords = oldRecords;
	}

	public void afterInsert()
	{
		updateLastPublishedDateOnPublisherFromRecentPublishedBook();
	}

	public void afterUpdate()
	{
		updateLastPublishedDateOnPublisherFromRecentPublishedBook();
	}

	public void afterDelete()
	{
		updateLastPublishedDateOnPublisherFromRecentPublishedBook();
	}
    
    public void afterUnDelete()
	{
		updateLastPublishedDateOnPublisherFromRecentPublishedBook();
	}

	private void updateLastPublishedDateOnPublisherFromRecentPublishedBook()
	{
		
		Map<Id, Publishing_House__c> publisherMap = new Map<Id, Publishing_House__c> ();

		List<AggregateResult> publishedDates = selectMaxPublishedDates(getPublisherIds());

		if (publishedDates.isEmpty())
		{
			return;
		}
		else
		{
			getMaxPublishDateByPublisher(publishedDates, publisherMap);
		}

		if (!publisherMap.values().isEmpty())
		{
			update(publisherMap.values());
		}
	}

	private void getMaxPublishDateByPublisher
			(List<AggregateResult> publishedDates, Map<Id, Publishing_House__c> publisherMap)
	{
		for (AggregateResult result : publishedDates)
		{
			publisherMap.put((Id) result.get('Publishing_House__C'),
					new Publishing_House__C(Id = (Id) result.get('Publishing_House__C'),
							Last_Published_Date__c = (Date) result.get('expr0')
					)
			);
		}
	}

	private List<AggregateResult> selectMaxPublishedDates(Set<Id> publisherId)
	{
		List<AggregateResult> publishedDates =
		[
				SELECT
						MAX(Publishing_Date__c),
						Publishing_House__C
				FROM Book__C
				WHERE Publishing_House__C IN :publisherId
				GROUP BY Publishing_House__C
		];
		return publishedDates;
	}

	private Set<Id> getPublisherIds()
	{
		Set<Id> publisherId = new Set<Id> ();

		if (Trigger.isDelete)
		{
			getPublisherIdSet(oldRecords, publisherId);
		}
		else
		{
			getPublisherIdSet(records, publisherId);
		}
		return publisherId;
	}

	private void getPublisherIdSet(List<Book__c> bookRecords, Set<Id> publisherIdSet)
	{
		for (Book__c record : bookRecords)
		{
			publisherIdSet.add(record.Publishing_House__c) ;
		}
	}
}